title: Goofy Ahh Website
author: Alvin L Hakim
email: alvinlhakim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
BREAKING NEWS desc are hard 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  AlvinLHakim # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
